name: Test and Notify

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          # Запуск тестов
          npm install
          npm test
      - name: Notify Project 2
        if: success()
        run: |
          git pull origin develop --allow-unrelated-histories

          # Отправка запроса в репозиторий проекта test2 для начала синхронизации
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/DimonONE/test2/dispatches \
            -d '{"event_type": "sync_with_project_a"}'
