name: Sync Develop Branch

on:
  push:
    branches:
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Set up Git
        run: |
          git config --global user.name "DimonONE"
          git config --global user.email "dimonmezey@gmail.com"
